# model
model: Qwen/Qwen2.5-1.5B
yarn:
  origin_seq_length: 2048

# dataset
dataset_dir: examples/data
dataset: llm_pretrain_demo, llm_sft_demo
packing: true
max_seq_length: 6144
#split_batches: true
reader_worker: auto
online_cache_path: saves/test/midtrain/online_cache
preprocessing_num_workers: 1
preprocessing_batch_size: 128

# training
task: midtrain
num_train_epochs: 1  

per_device_train_batch_size: 8 #24
gradient_accumulation_steps: 8

#warmup_ratio: 0.01
warmup_steps: 200
learning_rate: 2.0e-4 # 模型越大，学习率越小，GPT3从125M的 6.0e-4，降低到175B的 0.6e-4
lr_scheduler_type: cosine_with_min_lr #constant constant_with_warmup cosine cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr: 1.0e-5
  #min_lr_rate: 0.05

bf16: true
logging_steps: 10
deepspeed: configs/deepspeed/ds_z2_config.json
gradient_checkpointing: true

# other
seed: 19990723
save_steps: 500
output_dir: saves/test/midtrain
save_total_limit: 5
report_to: none #swanlab
log_level: info

# custom
# loss: 
#   type: domain_loss
#   domain_mapping:
#     1: "origin"
#     2: "copy"